CREATE DATABASE mailservice;
\c mailservice;

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender VARCHAR(10),
    birthday DATE,
    phone_number VARCHAR(15) UNIQUE
);


CREATE TABLE accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_address VARCHAR(255) UNIQUE NOT NULL,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    password TEXT NOT NULL,
    status TEXT,
    recovery_email VARCHAR(255),
    image_url VARCHAR(255)
);

CREATE TABLE reports (
    reporter_id BIGINT REFERENCES accounts(account_id) ON DELETE CASCADE,
    reported_user_id BIGINT REFERENCES accounts(account_id) ON DELETE CASCADE,
    reason TEXT NOT NULL,
    report_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(reporter_id, reported_user_id)
);


CREATE TABLE contacts (
    contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES accounts(account_id) ON DELETE CASCADE,
    contact_email VARCHAR(255) NOT NULL
);



CREATE TABLE emails (
    email_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT REFERENCES accounts(account_id) ON DELETE CASCADE,
    subject TEXT,
    body TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP,
    is_important BOOLEAN DEFAULT FALSE,
    attchments TEXT

);

CREATE TABLE email_recipients (
    recipient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_id BIGINT REFERENCES emails(email_id) ON DELETE CASCADE,
    recipient_email VARCHAR(255) REFERENCES accounts(email_address) ON DELETE CASCADE,
	    is_muted BOOLEAN
);



CREATE TABLE smtp_credentials (
    smtp_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    account_id BIGINT REFERENCES accounts(account_id) ON DELETE CASCADE,
    email_address VARCHAR(255) NOT NULL,
    smtp_password TEXT NOT NULL
);

CREATE TABLE admins (
    admin_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email_address VARCHAR(255) NOT NULL,
    password TEXT NOT NULL
);



CREATE TABLE attachments (
    attachment_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email_id BIGINT REFERENCES emails(email_id) NOT NULL,
    attachment_url TEXT NOT NULL
);
