version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  media-service:
    build:
      context: ../media-service
      dockerfile: Dockerfile
    container_name: media_service
    environment:
      - DATABASE_URL=mongodb://mongo:27017
      - DATABASE_NAME=emailserviceMediaDB
      - FILE_STORAGE_PATH=app/media
      - IAM_URL=http://iam.localhost:9000
      - GRPC_PORT=50051
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media-service.rule=Host(`media.localhost`)"
      - "traefik.http.services.media-service.loadbalancer.server.port=80"
    restart: unless-stopped
    ports:
      - "50051:50051" # gRPC port
    depends_on:
      - mongo

networks:
  backend:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  letsencrypt:
  esdata:
  mongo-data:
